// Builds the publishable `@supanadit/morse-web` package.
//
// The package ships exactly two things:
//
//   dist/server.mjs   one ESM bundle of the NestJS composition root, with every
//                     `@morse/*` workspace package inlined. Only the NestJS
//                     runtime stays external and is installed by npm from
//                     `dependencies`.
//   dist/cli.mjs      the `morse` lifecycle CLI (daemon, pidfile, logs).
//   dist/ui/          the built Angular frontend, served by the server as-is.
//
// Bundling is what turns a nine-package monorepo into a single npm artifact:
// the `@morse/*` packages are `private`, so they can never be resolved from the
// registry — but they are all pure ESM TypeScript libraries, so inlining them
// costs nothing at runtime.
//
// Prerequisites (run from the repo root before publishing):
//   npm run build:libs   # @morse/protocol, core, host-runtime, adapter-pi-rpc
//   npm run build:ui     # @morse/ui-angular -> packages/ui-angular/dist
//
// Usage:
//   node build.mjs                 # server + cli + ui
//   node build.mjs --server --cli  # skip the (slow) frontend copy
//   node build.mjs --ui
import { cp, mkdir, rm, stat } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const packagesRoot = join(here, '..');
const distDir = join(here, 'dist');

const flags = process.argv.slice(2).filter((value) => value.startsWith('--'));
const selected = new Set(flags.map((value) => value.slice(2)));
const wants = (name) => selected.size === 0 || selected.has(name);

/**
 * The NestJS runtime is the only thing `npm install` has to fetch; everything
 * under `@morse/` is workspace code and gets bundled. `platform: 'node'` keeps
 * `node:*` builtins external automatically.
 */
const runtimeExternals = ['@nestjs/*', 'reflect-metadata', 'rxjs', 'rxjs/*', 'ws', 'node-pty'];

async function requireBuild(path, hint) {
  try {
    await stat(path);
  } catch {
    console.error(`[morse-web] missing ${path}\n            ${hint}`);
    process.exit(1);
  }
}

async function bundleServer() {
  await Promise.all([
    requireBuild(
      join(packagesRoot, 'core', 'dist', 'index.js'),
      'Build the libraries first: npm run build:libs',
    ),
    requireBuild(
      join(packagesRoot, 'adapter-pi-rpc', 'dist', 'index.js'),
      'Build the libraries first: npm run build:libs',
    ),
    requireBuild(
      join(packagesRoot, 'host-runtime', 'dist', 'index.js'),
      'Build the libraries first: npm run build:libs',
    ),
  ]);

  await mkdir(distDir, { recursive: true });
  await build({
    entryPoints: [join(packagesRoot, 'server', 'src', 'main.ts')],
    outfile: join(distDir, 'server.mjs'),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    sourcemap: true,
    external: runtimeExternals,
    tsconfig: join(packagesRoot, 'server', 'tsconfig.json'),
    logLevel: 'info',
    banner: {
      js: '// Generated by packages/morse-web/build.mjs — do not edit.',
    },
  });
  console.log('[morse-web] server.mjs');
}

async function bundleCli() {
  await mkdir(distDir, { recursive: true });
  await build({
    entryPoints: [join(here, 'src', 'cli.ts')],
    outfile: join(distDir, 'cli.mjs'),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    sourcemap: true,
    external: runtimeExternals,
    logLevel: 'info',
    banner: { js: '#!/usr/bin/env node' },
  });
  console.log('[morse-web] cli.mjs');
}

async function copyUi() {
  const source = join(packagesRoot, 'ui-angular', 'dist');
  await requireBuild(
    join(source, 'webview.manifest.json'),
    'Build the frontend first: npm run build:ui',
  );
  const target = join(distDir, 'ui');
  await rm(target, { recursive: true, force: true });
  await mkdir(target, { recursive: true });
  await cp(source, target, { recursive: true });
  console.log('[morse-web] ui/');
}

const jobs = [];
if (wants('cli')) jobs.push(bundleCli());
if (wants('server')) jobs.push(bundleServer());
if (wants('ui')) jobs.push(copyUi());
await Promise.all(jobs);

console.log('[morse-web] ready: dist/{server.mjs,cli.mjs,ui/}');
